Controllers/GmailController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace MyPortfolio1.Controllers;

public class GmailController : Controller
{
    private readonly DataContext dbContext;

    public GmailController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }


    public IActionResult Register()
    {
        return View();
    } 

    [HttpPost]
    public IActionResult SendRegister(User odam)
    {
        odam.Link = "fbvcb";
        odam.name = "davcvxc";
        dbContext.Users.Add(odam);
        dbContext.SaveChanges();
        
            List<Claim> claims = new List<Claim>()
        { 
            new Claim(ClaimTypes.NameIdentifier, odam.Mail),
            new Claim("OtherProperties","Example Role")
        };

        ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        { 
            AllowRefresh = true,
            IsPersistent = true
        };
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);
        return RedirectToAction("Index", "User");
    }

    [HttpGet]
        public IActionResult Email()
    {
        return View();
    }
   [HttpPost]
   public IActionResult SendMail (User odam)
   {
    var user = dbContext.Users.FirstOrDefault(t => t.Mail == odam.Mail && t.Password == odam.Password);
   
    List<Claim> claims = new List<Claim>()
    {
        new Claim(ClaimTypes.Email, user.Mail),
        new Claim("FirstName", user.FirstName),
        new Claim("OtherProperties", "Example Role")
    };
            
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        { 
            AllowRefresh = true,
            IsPersistent = true
        };
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);
        
       return RedirectToAction("Index", "User");

   }

}

Views/Gmail/Email.cshtml
@* @{
    Gmail_Layout.cshtml = "Gmail_Layout.cshtml";
} *@

<style>
.screen-1 {
 
  padding: 2em;
  display: flex;
  flex-direction: column;
  border-radius: 30px;
  gap: 2em;
  background: #f1f7fe;
}

.screen-1:hover{
  box-shadow: 0 0 2em #e6e9f9;
}
.screen-1 .logo {
  margin-top: -3em;
}
.screen-1 .email {
  background: white;
  box-shadow: 0 0 2em #e6e9f9;
  padding: 1em;
  display: flex;
  flex-direction: column;
  gap: 0.5em;
  border-radius: 20px;
  color: #4d4d4d;
  margin-top: -3em;
}
.screen-1 .email input {
  outline: none;
  border: none;
}
.screen-1 .email input::-moz-placeholder {
  color: black;
  font-size: 0.9em;
}
.screen-1 .email input:-ms-input-placeholder {
  color: black;
  font-size: 0.9em;
}
.screen-1 .email input::placeholder {
  color: black;
  font-size: 0.9em;
}
.screen-1 .email ion-icon {
  color: #4d4d4d;
  margin-bottom: -0.2em;
}
.screen-1 .password {
  background: white;
  box-shadow: 0 0 2em #e6e9f9;
  padding: 1em;
  display: flex;
  flex-direction: column;
  gap: 0.5em;
  border-radius: 20px;
  color: #4d4d4d;
}
.screen-1 .password input {
  outline: none;
  border: none;
}
.screen-1 .password input::-moz-placeholder {
  color: black;
  font-size: 0.9em;
}
.screen-1 .password input:-ms-input-placeholder {
  color: black;
  font-size: 0.9em;
}
.screen-1 .password input::placeholder {
  color: black;
  font-size: 0.9em;
}
.screen-1 .password ion-icon {
  color: #4d4d4d;
  margin-bottom: -0.2em;
}
.screen-1 .password .show-hide {
  margin-right: -5em;
}
.screen-1 .login {
  padding: 1em;
  background: #3e4684;
  color: white;
  border: none;
  border-radius: 30px;
  font-weight: 600;
}
.screen-1 .footer {
  display: flex;
  font-size: 0.7em;
  color: #5e5e5e;
  gap: 14em;
  padding-bottom: 10em;
}
.screen-1 .footer span {
  cursor: pointer;
}

button {
  cursor: pointer;
} 
</style>

<form asp-action="SendMail" asp-controller="Gmail" method="post">
<!-- partial:index.partial.html -->
<div class="screen-1">
  <svg class="logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  width="200" height="200" viewbox="0 0 640 480" xml:space="preserve"> 
  </svg>
  <div class="email">
  
    <label for="Mail">Email Address</label>
    <div class="sec-2">
      <ion-icon name="mail-outline"></ion-icon>
      <input type="Mail" name="Mail" placeholder="Username@gmail.com"/>
    </div>
  </div>
  <div class="password">
    <label for="Password">Password</label>
    <div class="sec-2">
      <ion-icon name="lock-closed-outline"></ion-icon>
      <input class="pas" type="Password" name="Password" placeholder="············"/>
      <ion-icon class="show-hide" name="eye-outline"></ion-icon>
    </div>
  </div>
  <a href="Views/Gmail/Register"><button class="login">Logins</button></a>
  </form>