Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio1.Controllers;

public class ActorController : Controller
{
    private readonly DataContext dbContext;
    public ActorController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }

    public IActionResult Index()
    {
        List<Actor> actors = new List<Actor>();
         actors = dbContext.Actors.ToList();
        return View(actors);
    } 

    [HttpGet]
    public IActionResult Create()
    {
    return View();
    }

    [HttpGet]
    [Route("[controller]/[action]/{id}")]
    public IActionResult Edit(int Id)
    {
        var actor = dbContext.Actors.Find(Id);
        return View(actor);
    }
    
    [HttpPost]
    public IActionResult Update(int id, Actor newActor)
    {
        var oldActor = dbContext.Actors.Find(id);

        oldActor.Name = newActor.Name;
        dbContext.SaveChanges();
        
        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Store(Actor actor)
    {
        dbContext.Actors.Add(actor);
        dbContext.SaveChanges();
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    [Route("[controller]/[action]/{Id}")]
    public IActionResult Delete(int Id)
    {
        var actor = dbContext.Actors.Find(Id);
        dbContext.Actors.Remove(actor);
        dbContext.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace MyPortfolio1.Controllers;

public class AuthController : Controller
{
    private readonly DataContext dbContext;

    public AuthController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }


    public IActionResult Register()
    {
        return View();
    } 

    [HttpPost]
    public IActionResult SendRegister(User odam)
    {
        dbContext.Users.Add(odam);
        dbContext.SaveChanges();
        
            List<Claim> claims = new List<Claim>()
        { 
            new Claim(ClaimTypes.NameIdentifier, odam.Mail),
            new Claim("OtherProperties","Example Role")
        };

        ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        { 
            AllowRefresh = true,
            IsPersistent = true
        };
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);
        return RedirectToAction("Index", "User");
    }

    [HttpGet]
    public IActionResult Email()
    {
        return View();
    }
   [HttpPost]
   public IActionResult SendMail (User odam)
   {
    var user = dbContext.Users.FirstOrDefault(t => t.Mail == odam.Mail && t.Password == odam.Password);
    if(user == null)
    {
        return RedirectToAction("Email");
    }

    List<Claim> claims = new List<Claim>()
    {
        new Claim(ClaimTypes.Email, user.Mail),
        new Claim("FirstName", user.FirstName),
        new Claim("OtherProperties", "Example Role")
    };
            
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        { 
            AllowRefresh = true,
            IsPersistent = true
        };
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);
        
       return RedirectToAction("Index", "User");

   }
   public IActionResult Logout()
   {
    HttpContext.SignOutAsync();
    return RedirectToAction("Index", "Home");
   }

}

Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio1.Controllers;

public class GenreController : Controller
{
 private readonly DataContext dbContext;

    public GenreController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }
     public IActionResult Create()
     {
        return View();
     }

       public IActionResult Index()
    {
        List<Genre> genres = new List<Genre>();
         genres = dbContext.Genres.ToList();
        return View(genres);
    } 
        [HttpGet]
    [Route("[controller]/[action]/{id}")]
     public IActionResult Edit(int Id)
     {
        var genre = dbContext.Genres.Find(Id);
        return View(genre);
     }

    
    [HttpPost]
     public IActionResult Update(int id, Genre newGenre)
    {
        var oldGenre = dbContext.Genres.Find(id);

        oldGenre.Name = newGenre.Name;
        dbContext.SaveChanges();
        
        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Store(Genre genre)
    {
        dbContext.Genres.Add(genre);
        dbContext.SaveChanges();
        return RedirectToAction("Index");
    }
    
    [Route("[controller]/[action]/{Id}")]
    public IActionResult Delete(int Id)
    {
        var genre = dbContext.Genres.Find(Id);
        dbContext.Genres.Remove(genre);
        dbContext.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace MvcMyPortfolio1.Controllers;

public class MovieController : Controller
{
private readonly DataContext dbContext;
    
     public MovieController(DataContext dataContext)
     { 
        this.dbContext = dataContext;
     }
    public IActionResult Kino()
    {
        return View();
    }

       public IActionResult Index()
    {
        List<Movie> movies = new List<Movie>();
         movies = dbContext.Movies.ToList();
        return View(movies);
    } 

     
//   [Authorize]
  public IActionResult Create()
    {  
        return View();
    }

    [HttpPost]
    public IActionResult Store(Movie movie)
    {
        dbContext.Movies.Add(movie);
        dbContext.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("[controller]/[action]/{id}")]
     public IActionResult Edit(int Id)
     {
        var kino = dbContext.Movies.Find(Id);
        return View(kino);
     }

    
    [HttpPost]
     public IActionResult Update(int id, Movie newMovie)
    {
        var oldMovie = dbContext.Movies.Find(id);

        oldMovie.Name = newMovie.Name;
        oldMovie.Country = newMovie.Country;
        oldMovie.Year = newMovie.Year;

        dbContext.SaveChanges();
        
        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("[controller]/[action]/{id}")]
    public IActionResult Delete(int id)
    {
        var movie = dbContext.Movies.Find(id);
        dbContext.Movies.Remove(movie);
        dbContext.SaveChanges();
        return RedirectToAction("Index");
    }
}

Views/Shared/Gmail_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMyPortfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcMyPortfolio.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/rasm/OFAAX40.jpg">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>
<body style="background: rgb(33, 32, 32); ">
    <header>

            @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcMyPortfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMyPortfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcMyPortfolio.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/rasm/OFAAX40.jpg">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMyPortfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Kinopoisk">Kinopoisk</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Create">kino add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">User add</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Create">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actor" asp-action="Create">Actor</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                          {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">@User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.Email).Value</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Exit</a>
                        </li>
                          }
                       else
                       {
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Email">Sign-in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Sign-up</a>
                        </li>
                       }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcMyPortfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>